<?php
/**
 * Created by IntelliJ IDEA.
 * User: hezhongli
 * Date: 18/6/23
 * Time: 下午4:06
 */

namespace app\models;

use Pheasant\Types;

class TodoModel  extends BaseModel
{
    public function tableName()
    {
        return 'todo';
    }

    public function properties()
    {
        return array(
            'id' => new Types\SequenceType(),
            'title' => new Types\StringType(255,'required'),
            'status' => new Types\BooleanType(),
        ); // TODO: Change the autogenerated stub
    }
}